/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/setup/state": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read State */
        readonly get: operations["read_state_api_setup_state_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/installation": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read Installation */
        readonly get: operations["read_installation_api_setup_installation_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/sources": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Choose Sources
         * @description Write the library's folders into the config file and open the library under them.
         *
         *     Raises:
         *         HTTPException: 409 while a build runs, and 422 when the folders fail validation, naming what to change
         *             in the validators' own sentences.
         */
        readonly put: operations["choose_sources_api_setup_sources_put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/options": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Choose Options
         * @description Write how the library is built and whom it opens to into the config file, which the next build and start read.
         *
         *     Raises:
         *         HTTPException: 409 before any folders are saved, and 422 when the config file fails validation.
         */
        readonly put: operations["choose_options_api_setup_options_put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/builds": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Start Build
         * @description Start building the library, and answer with the state the build shows in.
         *
         *     Raises:
         *         HTTPException: 409 while the library is closed or another build runs.
         */
        readonly post: operations["start_build_api_setup_builds_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/builds/cancel": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Cancel Build */
        readonly post: operations["cancel_build_api_setup_builds_cancel_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/places": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read Places */
        readonly get: operations["read_places_api_setup_places_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/folders": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Read Folder
         * @description One folder's contents for the folder browser.
         *
         *     Raises:
         *         HTTPException: 404 when the path names no folder the system lets this application list.
         */
        readonly get: operations["read_folder_api_setup_folders_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/quit": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Quit Application
         * @description Close the library, with its build, renderer and managed database, then let the server stop.
         *
         *     The answer comes once the library is closed, so a start of another installation waiting for this
         *     one to quit opens the same library the moment the port comes free.
         */
        readonly post: operations["quit_application_api_setup_quit_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BuildDevice
         * @description What a build's steps compute on: an NVIDIA card by name, or the processor where `card` is None.
         */
        readonly BuildDevice: {
            /** Card */
            readonly card: string | null;
        };
        /** BuildRequest */
        readonly BuildRequest: {
            readonly target: components["schemas"]["BuildTarget"];
        };
        /**
         * BuildTarget
         * @description What a person asks the application to build: the catalog of their folders, or the whole library with its cloud.
         * @enum {string}
         */
        readonly BuildTarget: "catalog" | "all";
        /** Folder */
        readonly Folder: {
            /** Name */
            readonly name: string;
            /** Path */
            readonly path: string;
        };
        /**
         * FolderListing
         * @description One folder as the folder browser shows it: the folders inside it, and how many modules and audio files it holds itself.
         *
         *     The counts cover the folder's own files, which is what a person needs to recognize a collection
         *     while the listing stays quick on a large one.
         */
        readonly FolderListing: {
            /** Path */
            readonly path: string;
            /** Parent */
            readonly parent: string | null;
            /** Folders */
            readonly folders: readonly components["schemas"]["Folder"][];
            /** Module Files */
            readonly module_files: number;
            /** Audio Files */
            readonly audio_files: number;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * HomeNetworkReach
         * @description Whether this run of the application answers the devices on the home network, and the address they open it at.
         *
         *     It holds from the start of the run to its end, whatever the config says meanwhile. ``address``
         *     is None while this computer is on no home network.
         */
        readonly HomeNetworkReach: {
            /** Open */
            readonly open: boolean;
            /** Address */
            readonly address: string | null;
        };
        /**
         * Installation
         * @description Which installation of the application a running server belongs to: its version and its Python environment.
         *
         *     Each launcher installs its own environment, so the processor launcher, the NVIDIA one and a
         *     source checkout each report a different one, and so does every new version.
         */
        readonly Installation: {
            /** Version */
            readonly version: string;
            /** Environment */
            readonly environment: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        readonly JobStatus: "running" | "completed" | "failed" | "canceled";
        /**
         * JobView
         * @description One build as the application shows it: its steps in order, the running step's progress, and why it failed.
         */
        readonly JobView: {
            readonly target: components["schemas"]["BuildTarget"];
            readonly status: components["schemas"]["JobStatus"];
            /**
             * Started At
             * Format: date-time
             */
            readonly started_at: string;
            /** Ended At */
            readonly ended_at: string | null;
            /** Steps */
            readonly steps: readonly components["schemas"]["StepView"][];
            readonly problem: components["schemas"]["Problem"] | null;
            /** Log Tail */
            readonly log_tail: readonly string[];
        };
        /**
         * LibraryOptions
         * @description How the application builds and serves a person's library.
         *
         *     ``build_cloud`` says whether its builds go on past the catalog to the cloud, and
         *     ``open_to_network`` whether the devices on the home network may open the library too, to look.
         */
        readonly LibraryOptions: {
            /** Build Cloud */
            readonly build_cloud: boolean;
            /** Open To Network */
            readonly open_to_network: boolean;
        };
        /**
         * LibrarySources
         * @description What a person chooses for their library: where it lives, and the folders it reads modules and samples from.
         *
         *     The application writes these into the config file for a person who never opens it, and reads
         *     them back to show what the library holds.
         */
        readonly LibrarySources: {
            /**
             * Library Root
             * Format: path
             */
            readonly library_root: string;
            /** Module Source Directory */
            readonly module_source_directory: string | null;
            /** Sample Directories */
            readonly sample_directories: readonly string[];
            /** Sample Exclusions */
            readonly sample_exclusions: readonly string[];
        };
        /**
         * LibraryStatus
         * @description Where the application stands with its library: waiting for a person's choices, opening it, open, or stuck.
         * @enum {string}
         */
        readonly LibraryStatus: "unconfigured" | "starting" | "ready" | "failed";
        /**
         * MessageCode
         * @description What went wrong, named for the web app to word in the person's language.
         * @enum {string}
         */
        readonly MessageCode: "not_admitted" | "not_found" | "unreadable_audio" | "morph_unavailable" | "morph_timed_out" | "morph_refused" | "curation_withheld" | "too_many_requests" | "too_many_morphs" | "morphs_busy" | "library_not_open" | "library_in_use" | "library_open_failed" | "public_library_refused" | "save_folders_first" | "build_in_progress" | "build_already_running" | "build_step_stopped" | "build_refused" | "folder_not_a_folder" | "folder_unreadable" | "folder_not_absolute" | "folders_overlap" | "exclusion_empty" | "settings_invalid" | "configuration_refused";
        /**
         * Place
         * @description A folder the folder browser offers as a starting point: a person's own folders, and every drive.
         */
        readonly Place: {
            /** Name */
            readonly name: string;
            /** Path */
            readonly path: string;
        };
        /**
         * Problem
         * @description One thing that went wrong, as the web app words it: a code, the values its sentence names, and the technical reason.
         *
         *     The ``reason`` holds the plain technical sentence for a reader who can use it; the web app shows
         *     it beside its own wording of the code.
         */
        readonly Problem: {
            readonly code: components["schemas"]["MessageCode"];
            /** Params */
            readonly params: {
                readonly [key: string]: string | number;
            };
            /** Reason */
            readonly reason: string | null;
        };
        /**
         * ProgressReport
         * @description How far one pass has come, as the program watching it reads it: what it counts, how many are done, of how many.
         *
         *     `resumed` is how many were done already when this pass started, taken up from a pass stopped
         *     before it. The pass's start, the moment of its count and the count it added itself give the
         *     pace the watching program estimates the pass's remaining time from.
         */
        readonly ProgressReport: {
            /** Label */
            readonly label: string;
            /** Done */
            readonly done: number;
            /** Total */
            readonly total: number;
            /** Resumed */
            readonly resumed: number;
            /**
             * Started At
             * Format: date-time
             */
            readonly started_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /**
         * SetupState
         * @description What the setup pages show: the library's status, the sources chosen for it, and what went wrong if anything did.
         *
         *     `build_device` stays None until the application has asked which device builds compute on.
         */
        readonly SetupState: {
            readonly status: components["schemas"]["LibraryStatus"];
            /** Config Path */
            readonly config_path: string;
            readonly sources: components["schemas"]["LibrarySources"] | null;
            readonly options: components["schemas"]["LibraryOptions"] | null;
            readonly build_device: components["schemas"]["BuildDevice"] | null;
            /** Suggested Library Root */
            readonly suggested_library_root: string;
            /** Manages Database */
            readonly manages_database: boolean | null;
            readonly problem: components["schemas"]["Problem"] | null;
            readonly build: components["schemas"]["JobView"] | null;
            readonly home_network: components["schemas"]["HomeNetworkReach"];
        };
        /**
         * StepState
         * @description Where one step of a build stands, as a person reads it off the build's checklist.
         * @enum {string}
         */
        readonly StepState: "waiting" | "up to date" | "running" | "done" | "failed" | "skipped";
        /**
         * StepView
         * @description One step of a build: where it stands, when its latest attempt started and ended, and its running pass's count.
         */
        readonly StepView: {
            /** Name */
            readonly name: string;
            readonly state: components["schemas"]["StepState"];
            /** Started At */
            readonly started_at: string | null;
            /** Ended At */
            readonly ended_at: string | null;
            readonly progress: components["schemas"]["ProgressReport"] | null;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly read_state_api_setup_state_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
        };
    };
    readonly read_installation_api_setup_installation_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Installation"];
                };
            };
        };
    };
    readonly choose_sources_api_setup_sources_put: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LibrarySources"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly choose_options_api_setup_options_put: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LibraryOptions"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly start_build_api_setup_builds_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["BuildRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly cancel_build_api_setup_builds_cancel_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
        };
    };
    readonly read_places_api_setup_places_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Place"][];
                };
            };
        };
    };
    readonly read_folder_api_setup_folders_get: {
        readonly parameters: {
            readonly query: {
                readonly path: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["FolderListing"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly quit_application_api_setup_quit_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
}
